# Generated by Django 4.0.4 on 2022-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default=1, max_length=2, verbose_name='상태'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=80, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=80, verbose_name='제목'),
        ),
    ]
