# Generated by Django 4.0.4 on 2022-05-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_inquiry_state_alter_faq_content_alter_faq_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='is_eamil',
            new_name='is_email',
        ),
    ]
